### ISSUE TITLE
Provide support to split payments between multiple accounts

### ISSUE THREAD

**Issue by AlexisCaffa** [WhyNotHugo/django-mercadopago#14]
Provide ability to send, at the same time, a percentage of the payment to another mercado pago Account

**Comment by WhyNotHugo** [comment]
Does the API allow doing this? Otherwise it sounds like you need to create two `Preference`s, one with each account.

**Comment by AlexisCaffa** [comment]
Should be only one payment/preference.

I'm really not sure if it is possible. Apparently they tell me that yes. Through the `MarketPlace` there is a sort of commission for sellers, it could be done from there (?). First I will have to investigate.

But I leave the issue as an interesting new feature.

**Comment by WhyNotHugo** [comment]
Please provide a link to how this is implemented, if it's possible, and I might look into it.

**Comment by AlexisCaffa** [comment]
With a [marketplace](https://www.mercadopago.com.ar/developers/es/guides/marketplace/api/introduction)

I have managed to implement it. Only until I send the push, more verification and everything, it's a lot of delay and we need to start it now.

I had to perform horrorifics monkeypatches :(
_(One of the reasons is that I do not know how to install pip directly from github keeping the requirements saved, and then go back to the original pip version)_

In 2 weeks when I have more time we perfect this. It's very simple. You can achieve very broad things.

**Comment by WhyNotHugo** [comment]
Apparently, it's just a matter of configuring the account as a marketplace, and there's not difference in how `Preferece`s are created.

Docs are [here](https://www.mercadopago.com.ar/developers/es/guides/marketplace/api/introduction).

Did I miss something?

**Comment by AlexisCaffa** [comment]
Y los `Vendedores` se registran mediante un link, asi que hay que armar un end point para eso. Luego, el `MercadoPagoService` debería construirse de manera diferente para las cuentas marketplace, usando solo 1 parámetro, `access_token`, que corresponde al vendedor.

El `PeferenceManager.create` podría tener el parámetro `marketplace_fee` si se quiere.

Y viendo este funcionamiento se podría renombra los campos que se nombran en https://github.com/WhyNotHugo/django-mercadopago/issues/5 para que mantenga trazabilidad. 

Hablando en el aire, y si mal no recuerdo.

**Comment by AlexisCaffa** [comment]
I prefer to close this issue in order to leave the repository cleaner. This new feature extends the library too much, and I don't have the time to address it.

_Prefiero cerrar esta incidencia en pro de dejar el repositorio más limpio. Esta nueva característica extiende demasiado la librería, y no dispongo del tiempo para abordarlo._
