### ISSUE TITLE
Preference owner field change to account in the next major release

### ISSUE THREAD

**Issue by AlexisCaffa** [WhyNotHugo/django-mercadopago#17]
https://github.com/WhyNotHugo/django-mercadopago/blob/9c07a56d531ede6486ece0a55f90018cfab04deb/django_mercadopago/models.py#L200

Here is a typo error, must be `self.owner`, all the same I think it's more intuitive that the field is called `account` instead of `owner`.

**Comment by AlexisCaffa** [comment]
**submit Preference method typo error**

Solved in PR https://github.com/WhyNotHugo/django-mercadopago/pull/16

Issue title chaged by: _Preference owner field changed to account in the next major release_

**Comment by WhyNotHugo** [comment]
Fixed by #15.
