### ISSUE TITLE
Hola este proyecto sigue funcionando?

### ISSUE THREAD

**Issue by AlexCernik** [WhyNotHugo/django-mercadopago#26]
Buenas, no se si hablas español, pero quiero saber si sigue funcionando para tratar de utilizarlo. Hay alguna pagina que ya este usando esto? Es posible utilizar este código para construir un marketplace?

**Comment by WhyNotHugo** [comment]
Hay poco movimiento el repo pero es más que nada porque anda joya y no necesito hacerle mucho (sistemas bastante automatizados donde 

Si querés usar la funcionalidad de marketplace de mercadopago donde vos te quedás con una comisión de todo: eso no está implementado aún. Si te interesa sumar esa funcionalidad, cualquier PR es bienvenido; me parece que es lo idea si querés reusar toda la parte de pagos ya hecha.

Creo que lo hago habría que hacer es:

- Un modelo `Seller` que representa uno de esos vendedores.
  - Con un `ForeignKey` a account, donde ya hay lugar para la key y toda la lógica relacionada a autenticación.
- Un método que genere la URL para autenticación (`https://auth.mercadopago.com.ar/authorization?client_id=APP_ID&response_type=code&platform_id=mp&redirect_uri=https://www.URL_de_retorno.com`).
  - La URL de retorno debería tener el `id` del `Seller`.
  -  El parámetro `state` debería ser el `id` del seller [firmado](https://docs.djangoproject.com/en/3.0/topics/signing/#using-the-low-level-api)(para evitar spoofing y takeovers).
- Dos atributos a `Preference` `application_fee` y `seller_id`, ambos opcionales.
 - Pero `pre_save` debería chequear que si uno está seteado, el otro también debería estarlo o tirar `ValueError`.

El tema de notificaciones es todo igual por lo visto, así que no habría que hacerle nada.

[Docs](https://www.mercadopago.com.br/developers/en/guides/marketplace/api/create-marketplace/#editor_1594259106)

Si querés simplemente que muchos usuarios puedan vender con su cuenta, tendrían que generar un app_id y app_client en mercadolibre, y les hacés un form para que carguen eso.

**Comment by WhyNotHugo** [comment]
Huh, otro approach alternativo en: https://github.com/WhyNotHugo/django-mercadopago/issues/21#issuecomment-577006079

**Comment by AlexCernik** [comment]
Hola que tal Hugo, hoy que tuve tiempo me puse a tocar mi código y tengo una duda y un problema. Si tengo autoproces en True necesito usar celery? y a la hora de redirigir al usuario a mi pagina cuando el pago fue aprobado o no me da error, por favor me explicarías como es que tengo que hacerlo o que estoy haciendo mal?, este es mi código:

urls
`path('pay_ok/<id>/', views.pay_ok, name = 'payment_received'),`

views
`def pay_ok(request, id):
    return render(request, 'mercadopago/recivido.html')`

solamente tengo esto, ya que no se muy bien que es lo que tendría que poner en las funciones de los resultados.

Este es el error que me da:

`Reverse for 'payment_received' with keyword arguments '{'pk': 4}' not found. 1 pattern(s) tried: ['pay_ok\\/(?P<id>[^/]+)\\/$']`

**Comment by WhyNotHugo** [comment]
> Si tengo autoproces en True necesito usar celery?

No, si está en `True` procesa notificaciones de forma bloqueando durante el request.

Si está en `False`, **no** se procesan, y queda a cargo tuyo procesarlas. Siempre se dispara el signal `process_notification`, así que podés disparar celery desde ahí (es lo que suelo hacer).

---
El parámetro del primary key debería llamar `pk`

```python
path('pay_ok/<pk>/', views.pay_ok, name = 'payment_received'),
```

Fijate que eso es lo que te indica el error: que buscó una URL con kwargs `pk`, y  sólo encontró una con `id`.

**Comment by AlexCernik** [comment]
> > Si tengo autoproces en True necesito usar celery?
> 
> No, si está en `True` procesa notificaciones de forma bloqueando durante el request.
> 
> Si está en `False`, **no** se procesan, y queda a cargo tuyo procesarlas. Siempre se dispara el signal `process_notification`, así que podés disparar celery desde ahí (es lo que suelo hacer).
> 
> El parámetro del primary key debería llamar `pk`
> 
> ```python
> path('pay_ok/<pk>/', views.pay_ok, name = 'payment_received'),
> ```
> 
> Fijate que eso es lo que te indica el error: que buscó una URL con kwargs `pk`, y sólo encontró una con `id`.

Bien si, ponía el <pk> en la url pero era problema de mi función jaja gracias xD... Vi que la clase Preference tiene la función Update, y la estoy queriendo usar pero no me esta saliendo, hago uso del bucle for para recorrer los items en la orden pero el update solo me guarda un item , la verdad es que no se cual sería la forma mas optima de hacer todo el procedimiento, en este link [https://codeshare.io/5Mvv1Q](url) te dejo mi modelo y la función comprar que tengo hasta ahora, como para que me puedas decir que estoy haciendo mal o si todo esta mal xDD
