### ISSUE TITLE
Had integration with DRF

### ISSUE THREAD

**Issue by emidioandre** [WhyNotHugo/django-mercadopago#30]
This project have integration with DRF ?

**Comment by WhyNotHugo** [comment]
You don't _need_ DRF to use this. The API part is already implemented.
I do have projects where I use this **and** DRF, and there's no conflict.

That said, if you're starting a new integration, I'm currently contributing to [django-payments](https://github.com/jazzband/django-payments/pull/232), and have migrated a lot of the logic here into it.

Setup is a bit easier, and you immediately get support for other payment providers. The model is a lot cleaner and more understandable too.

`django-mercadopago` still works though, but obviously won't receive many new features or alike.

**Comment by emidioandre** [comment]
I'm a junior in this problem, and I have problems to integrate with mercado pago in DRF. I will see django-payments. 

Do you have a example in drf with django-mercadopago ?

**Comment by WhyNotHugo** [comment]
> Do you have a example in drf with django-mercadopago ?

DRF is for you service to expose a webservice. That is, to run a server with a REST API.

django-mercadopago is a library to connect to mercadolibre's API. It's a client that connect's to mercadolibre's existing API.

What are you trying to do?

**Comment by emidioandre** [comment]
w
