### ISSUE TITLE
Account help_text Mercado Pago utiliza otros nombres

### ISSUE THREAD

**Issue by AlexisCaffa** [WhyNotHugo/django-mercadopago#5]
``` po
msgid "The APP_ID given by MercadoPago."
msgstr "El APP_ID dato por MercadoPago."

msgid "The SECRET_KEY given by MercadoPago."
msgstr "El SECRET_KEY dado por MercadoPago."
```
`APP_ID` ahora es `CLIENT_ID`
y
`SECRET_KEY` ahora es `CLIENT_SECRET`

**Comment by WhyNotHugo** [comment]
Dónde viste ese cambio?

![2019-01-23t01 01 39 355704973-03 00](https://user-images.githubusercontent.com/730811/51582402-a6030480-1eaa-11e9-9a59-767a6108d952.png)

**Comment by AlexisCaffa** [comment]
Estaba usando estas [mercadopago.com/mla/account/credentials](https://www.mercadopago.com/mla/account/credentials), en la pestaña "Checkout básico" :sweat_smile:
![mercado pago credentials](https://user-images.githubusercontent.com/4590357/51584313-802e2d80-1eb3-11e9-9659-0798a70154af.png)

**Comment by AlexisCaffa** [comment]
Propongo:

* Opción A:
  1. Cambiar solo los `help_text`  para que los forms del admin queden más ameno.
   
* Opción B:
  1. Cambiar los `help_text` y los nombres de los campos  
  2. Crear metodos `@property` con los campos que se han cambiado para garantizar compatibilidad  
  3. Colocar un log/print con un mensaje de advertencia que los campos `app_id` y `secret_key` son `deprecated`
