### ISSUE TITLE
Grave problema al generar un Payment teniendo multiples Accounts

### ISSUE THREAD

**Issue by AlexisCaffa** [WhyNotHugo/django-mercadopago#8]
El modelo `Payment` tiene el campo `mp_id` como único y, al generarse pagos de `Accounts` diferentes es posible que vengan con la misma identificación generando así un:

`IntegrityError: (1062, "Duplicate entry '2147483647' for key 'mp_id'")`

Sugiero:
  a. Eliminar la [línea 351](https://github.com/WhyNotHugo/django-mercadopago/blob/b00e7f340fb86a7da89050cc22eb94638cac8f1c/django_mercadopago/models.py#L351) dejándolo libre sin validación.
  b. Agregar programáticamente algo similar a
 ``` python
class Meta:
    unique_together = (("mp_id", "preference__owner"),)
```

**Comment by WhyNotHugo** [comment]
Que raro no me topé con esto en producción en ningún momento.

Déjame que lo mire de cerca; puede que hayan otras partes del código que también asumen que es único (en especial al bajar pagos).

**Comment by AlexisCaffa** [comment]
¡Que suerte de tu parte! O que suerte la mía que a las primeras me sale eso..

Puedo estar equivocado y que ese problema no sea como supongo pero, lógicamente, al no tratarse de un campo UUID es muy probable que en algún momento, tarde o temprano, se genere un error de integridad ¿verdad?

**Comment by WhyNotHugo** [comment]
> Puedo estar equivocado y que ese problema no sea como supongo pero, lógicamente, al no tratarse de un campo UUID es muy probable que en algún momento, tarde o temprano, se genere un error de integridad ¿verdad?

No veo porque. Mercadolibre los documenta como UUID (aunque no lo son), pero sospecho que deben ser globalmente únicos de todas formas. ¿Te pasó realmente de que te llegaron pagos de múltiples cuentas con el mismo id?

**Comment by AlexisCaffa** [comment]
Este error es real, al momento de realizar un `poll_status`
`IntegrityError: (1062, "Duplicate entry '2147483647' for key 'mp_id'")`

**Comment by AlexisCaffa** [comment]
AH NO! El problema es que estoy usando MariaDB y el límite del `IntergerField` es `int(11)` :disappointed: 
``` SQL
mysql> DESCRIBE mp_payment;
+-----------------+-------------+------+-----+---------+----------------+
| Field           | Type        | Null | Key | Default | Extra          |
+-----------------+-------------+------+-----+---------+----------------+
| id              | int(11)     | NO   | PRI | NULL    | auto_increment |
| mp_id           | int(11)     | NO   |     | NULL    |                |
| status          | varchar(16) | NO   |     | NULL    |                |
| status_detail   | varchar(32) | NO   |     | NULL    |                |
| created         | datetime(6) | NO   |     | NULL    |                |
| approved        | datetime(6) | YES  |     | NULL    |                |
| preference_id   | int(11)     | NO   | MUL | NULL    |                |
| notification_id | int(11)     | YES  | UNI | NULL    |                |
+-----------------+-------------+------+-----+---------+----------------+
```

**Comment by WhyNotHugo** [comment]
Hmm, sí, eso está [documentado así](https://docs.djangoproject.com/en/dev/ref/models/fields/#integerfield), pero parece que es una limitación específica de MariaDB.

Debería ser un CharField, aunque el cambio debería traer migraciones que aseguren que no rompa nada en instalaciones existentes,

**Comment by WhyNotHugo** [comment]
Ah, sí, perdón, me confundí un poco con los largos de `Payment.mp_id` y `Preference.mp_id`.

`BigIntegerField` debería alcanzar; los `mp_id`s que estoy viendo no tienen drama con ese rango (por suerte!).
